apiVersion: karkive.io/v1alpha1
kind: Backup
metadata:
  name: cache-redis
  namespace: backup
spec:
  engine: redis
  schedule: "0 */12 * * *"
  database:
    host: redis.example.svc.cluster.local
    port: 6379
    name: cache
  s3:
    endpoint: https://s3.example.com
    bucket: backups
    path: cache/redisdump
    retentionDays: 14
  secretRef:
    name: backup-cache-redis
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: standard
  localRetentionDays: 7
